# Generated by Django 4.2.1 on 2023-05-29 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='follower',
            table='django_session',
        ),
    ]
