# Generated by Django 4.2.1 on 2023-05-29 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_follower_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
